### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-1-evaluacion-intermedia-SandraLarrosa#1]
Muy buen trabajo @SandraLarrosa!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 218 / 347
- [x] CARPETAS > CSS: La ruta del fichero CSS debe empezar por `./styles/` o `./css/`.
- [x] HTML > LINK: Debemos tener dos ficheros de estilos importados con un `link`.
- [x] HTML > HEADER: La etiqueta `img` debe tener el atributo `title`.
- [x] HTML > HEADER: Necesitamos al menos una etiqueta `header`.
- [x] HTML > HEADER: Necesitamos dos etiquetas `a` en el menu, dentro de los `li`.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Blog". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Contacto". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > MAIN: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.
- [x] CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos.
- [x] CSS > PADDING: El padding de los enlaces no debería ser 0. Auméntalo para aumentar el área clickable, pero manteniendo los requisitos del diseño.
- [x] CSS > CLASES: No se deben utilizar etiquetas CSS ni ids como selectores, salvo `a`, `html` y `body`.
- [x] CSS > CLASES: El fichero CSS no es correcto. Comprueba si has cerrado todas las llaves.
- [x] CSS > FLEX: El texto Creando diversidad digital debe estar centrado horizontal y verticalmente, lo mejor es hacerlo con flex.
- [x] CSS > FLEX: El HEADER en tablet debe tener los elementos alineados a izquierda y derecha .

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te enjaca dímelo cuanto antes por favor.

Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by SandraLarrosa** [comment]
¡Buenos días Miguel!
Ya he terminado de corregir los errores de la evaluación intermedia.
He tenido fallos muy tontos, pero seguro que la próxima vez no me vuelve a pasar.
Lo único que tengo dudas es en las siguientes partes:

**CARPETAS > CSS: La ruta del fichero CSS debe empezar por ./styles/ o ./css/.** -> Yo he llamado a la carpeta style, ya lo he cambiado para el ejercicio, pero me gustaría saber si siempre tiene que llamarse styles en plural. 

**HTML > LINK: Debemos tener dos ficheros de estilos importados con un link.** (Este es el que comentaste en clase.)

**CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos.** -> No encuentro los estilos repetidos en las media queries, creo que se me pasa algo y no lo veo.

**CSS > CLASES: No se deben utilizar etiquetas CSS ni ids como selectores, salvo a, html y body.** -> Aquí tenía aplicados estilos al html en general. Pero no sé en  realidad a que se refiere, porque creo que lo que puse estaba bien.

**CSS > CLASES: El fichero CSS no es correcto. Comprueba si has cerrado todas las llaves.** -> He revisado el CSS y no me falta ninguna llave, creo que no funcionaría si me faltase algo. Lo que he quitado ha sido los comentarios que tenía en la hoja de estilos diferenciando el Header y el Main. ¿Puede ser por eso?.

 **CSS > FLEX: El texto Creando diversidad digital debe estar centrado horizontal y verticalmente, lo mejor es hacerlo con flex.
 CSS > FLEX: El HEADER en tablet debe tener los elementos alineados a izquierda y derecha .** -> Estas dos cosas ya las tenía hechas desde el principio, pero no sé si se me pasa algo por alto.

¡¡¡Muchas gracias por todo!!!

**Comment by migueldelmazo** [comment]
Hola @SandraLarrosa, te voy contestando...

> CARPETAS > CSS: La ruta del fichero CSS debe empezar por ./styles/ o ./css/. -> Yo he llamado a la carpeta style, ya lo he cambiado para el ejercicio, pero me gustaría saber si siempre tiene que llamarse styles en plural.

No hace falta, esto lo ponemos para que lo metáis en alguna carpeta con un bueno nombre. En singular o plural está bien.

> HTML > LINK: Debemos tener dos ficheros de estilos importados con un link. (Este es el que comentaste en clase.).

Eso es.

> CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos. -> No encuentro los estilos repetidos en las media queries, creo que se me pasa algo y no lo veo.

Supongo que serían estos dos: https://github.com/Adalab/modulo-1-evaluacion-intermedia-SandraLarrosa/blob/2be3c82ccbdd43863a2e8543d2c62fd94a182413/style/style.css#L40 y https://github.com/Adalab/modulo-1-evaluacion-intermedia-SandraLarrosa/blob/2be3c82ccbdd43863a2e8543d2c62fd94a182413/style/style.css#L87 que ya lo tienes corregido.

> CSS > CLASES: No se deben utilizar etiquetas CSS ni ids como selectores, salvo a, html y body. -> Aquí tenía aplicados estilos al html en general. Pero no sé en realidad a que se refiere, porque creo que lo que puse estaba bien.

Nos referimos a este `li` por ejemplo https://github.com/Adalab/modulo-1-evaluacion-intermedia-SandraLarrosa/blob/master/styles/style.css#L50

> CSS > CLASES: El fichero CSS no es correcto. Comprueba si has cerrado todas las llaves. -> He revisado el CSS y no me falta ninguna llave, creo que no funcionaría si me faltase algo. Lo que he quitado ha sido los comentarios que tenía en la hoja de estilos diferenciando el Header y el Main. ¿Puede ser por eso?.

Este error sale porque le pasamos el [valdiador de la W3C](https://jigsaw.w3.org/css-validator/) y nos dice que hay errores. Este curso es el primero que enseñamos variables CSS. Pues resulta que al validador no le gustan las variables CSS :( Déjalo como está, está bien.

> CSS > FLEX: El texto Creando diversidad digital debe estar centrado horizontal y verticalmente, lo mejor es hacerlo con flex.

Pues aquí la he liado con el autocorrector, no hagas caso.

> CSS > FLEX: El HEADER en tablet debe tener los elementos alineados a izquierda y derecha . -> Estas dos cosas ya las tenía hechas desde el principio, pero no sé si se me pasa algo por alto.

No puedo comprobar lo que pasaba, he revisado lo que tienes ahora y está fetén.

Muy buen curro @SandraLarrosa !!!
